// Scans characters/*/phone and rewrites js/phones.js
const fs=require("fs"),path=require("path");
const root=path.join(__dirname,"..","characters"),IMG=/\.(png|jpe?g|gif|webp|svg)$/i,out={};
const imgs=d=>fs.existsSync(d)?fs.readdirSync(d).filter(f=>IMG.test(f)).sort():[];
for(const folder of fs.readdirSync(root)){
  const pj=path.join(root,folder,"profile.json"); if(!fs.existsSync(pj)) continue;
  const id=JSON.parse(fs.readFileSync(pj,"utf8")).id, ph=path.join(root,folder,"phone");
  const selfies=imgs(ph).filter(f=>/^selfie/i.test(f)).sort((a,b)=>/\.svg$/i.test(a)-/\.svg$/i.test(b));
  out[id]={folder,selfie:selfies[0]||"",photos:imgs(path.join(ph,"photos")),fromYou:imgs(path.join(ph,"from-you"))};
}
fs.writeFileSync(path.join(__dirname,"..","js","phones.js"),"/* generated by tools/scan-phones.js - do not edit by hand */\nwindow.LOBBY_PHONES="+JSON.stringify(out,null,1)+";\n");
console.log("phones.js written for "+Object.keys(out).length+" characters");
