/* generated by tools/scan-phones.js - do not edit by hand */
window.LOBBY_PHONES={
 "custom-allison": {
  "folder": "Allison - CORE",
  "selfie": "selfie-Allison.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-ame": {
  "folder": "Ame - CORE",
  "selfie": "selfie-Ame.svg",
  "photos": [],
  "fromYou": []
 },
 "amy": {
  "folder": "Amy - CORE",
  "selfie": "selfie-Amy.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-09": {
  "folder": "Angela - CORE",
  "selfie": "selfie-Angela.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-anja": {
  "folder": "Anja - CORE",
  "selfie": "selfie-Anja.svg",
  "photos": [],
  "fromYou": []
 },
 "net-15": {
  "folder": "AstroMorg - CORE",
  "selfie": "selfie-AstroMorg.svg",
  "photos": [],
  "fromYou": []
 },
 "net-19": {
  "folder": "Avery - CORE",
  "selfie": "selfie-Avery.svg",
  "photos": [],
  "fromYou": []
 },
 "becky": {
  "folder": "Becky - CORE",
  "selfie": "selfie-Becky.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-bobby": {
  "folder": "Bobby - CORE",
  "selfie": "selfie-Bobby.svg",
  "photos": [],
  "fromYou": []
 },
 "net-10": {
  "folder": "BookwormRobin - CORE",
  "selfie": "selfie-BookwormRobin.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-03": {
  "folder": "Brian - CORE",
  "selfie": "selfie-Brian.svg",
  "photos": [],
  "fromYou": []
 },
 "net-11": {
  "folder": "CamWebSurfer - CORE",
  "selfie": "selfie-CamWebSurfer.svg",
  "photos": [],
  "fromYou": []
 },
 "net-5": {
  "folder": "Casey - CORE",
  "selfie": "selfie-Casey.svg",
  "photos": [],
  "fromYou": []
 },
 "net-6": {
  "folder": "CinemaMorgan - CORE",
  "selfie": "selfie-CinemaMorgan.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-clayton": {
  "folder": "Clayton - CORE",
  "selfie": "selfie-Clayton.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-12": {
  "folder": "Daniel - CORE",
  "selfie": "selfie-Daniel.svg",
  "photos": [],
  "fromYou": []
 },
 "dave": {
  "folder": "Dave - CORE",
  "selfie": "selfie-Dave.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-david-jr": {
  "folder": "David Jr. - CORE",
  "selfie": "selfie-David Jr..svg",
  "photos": [],
  "fromYou": []
 },
 "custom-david-sr": {
  "folder": "David Sr. - CORE",
  "selfie": "selfie-David Sr..svg",
  "photos": [],
  "fromYou": []
 },
 "net-28": {
  "folder": "Devon - CORE",
  "selfie": "selfie-Devon.svg",
  "photos": [],
  "fromYou": []
 },
 "net-9": {
  "folder": "Drew_R - CORE",
  "selfie": "selfie-Drew_R.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-elijah": {
  "folder": "Elijah - CORE",
  "selfie": "selfie-Elijah.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-elizabeth": {
  "folder": "Elizabeth - CORE",
  "selfie": "selfie-Elizabeth.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-08": {
  "folder": "Eric - CORE",
  "selfie": "selfie-Eric.svg",
  "photos": [],
  "fromYou": []
 },
 "net-12": {
  "folder": "Erin - CORE",
  "selfie": "selfie-Erin.svg",
  "photos": [],
  "fromYou": []
 },
 "net-18": {
  "folder": "GhoulGirl13 - CORE",
  "selfie": "selfie-GhoulGirl13.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-gwen": {
  "folder": "Gwen - CORE",
  "selfie": "selfie-Gwen.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-02": {
  "folder": "Heather - CORE",
  "selfie": "selfie-Heather.svg",
  "photos": [],
  "fromYou": []
 },
 "net-23": {
  "folder": "InkMia - CORE",
  "selfie": "selfie-InkMia.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-01": {
  "folder": "Jason - CORE",
  "selfie": "selfie-Jason.svg",
  "photos": [],
  "fromYou": []
 },
 "jen": {
  "folder": "Jen - CORE",
  "selfie": "selfie-Jen.svg",
  "photos": [],
  "fromYou": []
 },
 "net-16": {
  "folder": "Jesse - CORE",
  "selfie": "selfie-Jesse.svg",
  "photos": [],
  "fromYou": []
 },
 "net-27": {
  "folder": "Jess_Shutter - CORE",
  "selfie": "selfie-Jess_Shutter.svg",
  "photos": [],
  "fromYou": []
 },
 "net-0": {
  "folder": "Jordan - CORE",
  "selfie": "selfie-Jordan.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-josh": {
  "folder": "Josh - CORE",
  "selfie": "selfie-Josh.svg",
  "photos": [],
  "fromYou": []
 },
 "net-22": {
  "folder": "Kelly - CORE",
  "selfie": "selfie-Kelly.svg",
  "photos": [],
  "fromYou": []
 },
 "kevin": {
  "folder": "Kevin - CORE",
  "selfie": "selfie-Kevin.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-16": {
  "folder": "Kim - CORE",
  "selfie": "selfie-Kim.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-06": {
  "folder": "Laura - CORE",
  "selfie": "selfie-Laura.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-11": {
  "folder": "Lauren - CORE",
  "selfie": "selfie-Lauren.svg",
  "photos": [],
  "fromYou": []
 },
 "lisa": {
  "folder": "Lisa - CORE",
  "selfie": "selfie-Lisa.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-00": {
  "folder": "Mandy - CORE",
  "selfie": "selfie-Mandy.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-05": {
  "folder": "Marcus - CORE",
  "selfie": "selfie-Marcus.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-13": {
  "folder": "Melissa - CORE",
  "selfie": "selfie-Melissa.svg",
  "photos": [],
  "fromYou": []
 },
 "mike": {
  "folder": "Mike - CORE",
  "selfie": "selfie-Mike.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-07": {
  "folder": "Monica - CORE",
  "selfie": "selfie-Monica.svg",
  "photos": [],
  "fromYou": []
 },
 "net-2": {
  "folder": "NightOwl77 - CORE",
  "selfie": "selfie-NightOwl77.svg",
  "photos": [],
  "fromYou": []
 },
 "net-29": {
  "folder": "OldFrank - CORE",
  "selfie": "selfie-OldFrank.svg",
  "photos": [],
  "fromYou": []
 },
 "net-3": {
  "folder": "Pat - CORE",
  "selfie": "selfie-Pat.svg",
  "photos": [],
  "fromYou": []
 },
 "net-8": {
  "folder": "PixelJamie - CORE",
  "selfie": "selfie-PixelJamie.svg",
  "photos": [],
  "fromYou": []
 },
 "net-14": {
  "folder": "PunnyBoy88 - CORE",
  "selfie": "selfie-PunnyBoy88.svg",
  "photos": [],
  "fromYou": []
 },
 "net-13": {
  "folder": "QuarterKing - CORE",
  "selfie": "selfie-QuarterKing.svg",
  "photos": [],
  "fromYou": []
 },
 "net-31": {
  "folder": "quiet_mark - CORE",
  "selfie": "selfie-quiet_mark.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-14": {
  "folder": "Rachel - CORE",
  "selfie": "selfie-Rachel.svg",
  "photos": [],
  "fromYou": []
 },
 "net-20": {
  "folder": "RefIsBlind - CORE",
  "selfie": "selfie-RefIsBlind.svg",
  "photos": [],
  "fromYou": []
 },
 "rick": {
  "folder": "Rick - CORE",
  "selfie": "selfie-Rick.svg",
  "photos": [],
  "fromYou": []
 },
 "net-17": {
  "folder": "Riley_G - CORE",
  "selfie": "selfie-Riley_G.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-robert": {
  "folder": "Robert - CORE",
  "selfie": "selfie-Robert.svg",
  "photos": [],
  "fromYou": []
 },
 "sarah": {
  "folder": "Sarah - CORE",
  "selfie": "selfie-Sarah.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-15": {
  "folder": "Sean - CORE",
  "selfie": "selfie-Sean.svg",
  "photos": [],
  "fromYou": []
 },
 "custom-shaunte": {
  "folder": "Shaunte - CORE",
  "selfie": "selfie-Shaunte.svg",
  "photos": [],
  "fromYou": []
 },
 "net-25": {
  "folder": "SitcomNicole - CORE",
  "selfie": "selfie-SitcomNicole.svg",
  "photos": [],
  "fromYou": []
 },
 "net-1": {
  "folder": "Skater_Chris - CORE",
  "selfie": "selfie-Skater_Chris.svg",
  "photos": [],
  "fromYou": []
 },
 "net-4": {
  "folder": "SolderFace - CORE",
  "selfie": "selfie-SolderFace.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-10": {
  "folder": "Stacy - CORE",
  "selfie": "selfie-Stacy.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-04": {
  "folder": "Stephanie - CORE",
  "selfie": "selfie-Stephanie.svg",
  "photos": [],
  "fromYou": []
 },
 "net-7": {
  "folder": "Taylor - CORE",
  "selfie": "selfie-Taylor.svg",
  "photos": [],
  "fromYou": []
 },
 "net-30": {
  "folder": "Tina - CORE",
  "selfie": "selfie-Tina.svg",
  "photos": [],
  "fromYou": []
 },
 "tony": {
  "folder": "Tony - CORE",
  "selfie": "selfie-Tony.svg",
  "photos": [],
  "fromYou": []
 },
 "net-24": {
  "folder": "Trevor_H - CORE",
  "selfie": "selfie-Trevor_H.svg",
  "photos": [],
  "fromYou": []
 },
 "net-extra-17": {
  "folder": "Victor - CORE",
  "selfie": "selfie-Victor.svg",
  "photos": [],
  "fromYou": []
 },
 "net-21": {
  "folder": "Win95Shawn - CORE",
  "selfie": "selfie-Win95Shawn.svg",
  "photos": [],
  "fromYou": []
 },
 "net-26": {
  "folder": "WrenchRyan - CORE",
  "selfie": "selfie-WrenchRyan.svg",
  "photos": [],
  "fromYou": []
 }
};
